"""Report generation + scheduling models (Module 8 — Reporting & Export)."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UuidMixin

# JSONB on Postgres, plain JSON elsewhere (SQLite in tests).
Json = JSON().with_variant(JSONB, "postgresql")

# Report types (spec 8.1 / 8.2).
TYPE_ORG_SUMMARY = "org_summary"
TYPE_MACHINE_DETAIL = "machine_detail"
REPORT_TYPES = (TYPE_ORG_SUMMARY, TYPE_MACHINE_DETAIL)

# Output formats.
FORMAT_PDF = "pdf"
FORMAT_CSV = "csv"
REPORT_FORMATS = (FORMAT_PDF, FORMAT_CSV)

# Generation lifecycle (spec 8.4).
STATUS_QUEUED = "queued"
STATUS_RUNNING = "running"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"


class Report(Base, UuidMixin, TimestampMixin):
    """A single generated (or in-flight) report artifact."""

    __tablename__ = "reports"
    __table_args__ = (
        Index("ix_reports_status", "status"),
        Index("ix_reports_type", "type"),
        Index("ix_reports_expires_at", "expires_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    format: Mapped[str] = mapped_column(String(10), nullable=False)
    # Extra config — e.g. {"machine_uuid": "...", "title": "..."}.
    params: Mapped[dict[str, Any]] = mapped_column(Json, nullable=False, default=dict)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default=STATUS_QUEUED)
    error_message: Mapped[str | None] = mapped_column(Text)
    file_path: Mapped[str | None] = mapped_column(Text)
    file_size: Mapped[int | None] = mapped_column(BigInteger)
    # NULL when generated by a schedule (system), set for user-initiated reports.
    generated_by_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    schedule_id: Mapped[int | None] = mapped_column(
        ForeignKey("report_schedules.id", ondelete="SET NULL")
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # For the 30-day retention cleanup job (spec 8.4 storage).
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class ReportSchedule(Base, UuidMixin, TimestampMixin):
    """A recurring report definition driven by a cron expression (spec 8.5)."""

    __tablename__ = "report_schedules"
    __table_args__ = (Index("ix_report_schedules_due", "is_active", "next_run_at"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    format: Mapped[str] = mapped_column(String(10), nullable=False)
    params: Mapped[dict[str, Any]] = mapped_column(Json, nullable=False, default=dict)
    cron: Mapped[str] = mapped_column(String(50), nullable=False)
    # Array of email addresses; Phase 5 delivers, v1 stores only.
    recipients: Mapped[list[str]] = mapped_column(Json, nullable=False, default=list)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_by_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
