run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gosec
    - revive
    - bodyclose
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters: [gosec, errcheck]
